"""Update projects table: rename size to form_factor and add memory column

Revision ID: 002_update_projects_size_to_form_factor
Revises: 001_initial_migration
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_update_projects_size_to_form_factor'
down_revision = '001_initial_migration'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Rename size column to form_factor
    op.alter_column('projects', 'size', new_column_name='form_factor')
    
    # Add memory column
    op.add_column('projects', sa.Column('memory', sa.String(length=100), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove memory column
    op.drop_column('projects', 'memory')
    
    # Rename form_factor column back to size
    op.alter_column('projects', 'form_factor', new_column_name='size')
    
    # ### end Alembic commands ###
