"""Add related_id and meeting_notes to VOC table

Revision ID: 003_add_voc_related_id_and_meeting_notes
Revises: 002_update_projects_size_to_form_factor
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003_add_voc_related_id_and_meeting_notes'
down_revision = '002_update_projects_size_to_form_factor'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add related_id column to VOC table
    op.add_column('vocs', sa.Column('related_id', sa.Integer(), nullable=False, server_default='0'))
    
    # Add meeting_notes column to VOC table
    op.add_column('vocs', sa.Column('meeting_notes', sa.Text(), nullable=True))
    
    # Create index for related_id for better query performance
    op.create_index(op.f('ix_vocs_related_id'), 'vocs', ['related_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop index for related_id
    op.drop_index(op.f('ix_vocs_related_id'), table_name='vocs')
    
    # Remove meeting_notes column
    op.drop_column('vocs', 'meeting_notes')
    
    # Remove related_id column
    op.drop_column('vocs', 'related_id')
    
    # ### end Alembic commands ###
